- name : ec2-launcher
  hosts : localhost
  connection : local
  tasks :
  - name : launch ec2
    ec2 : 
     instance_type : t2.micro
     key_name : MyMumbaiKey
     image : ami-0e306788ff2473ccb
     region : ap-south-1
     group : launch-wizard-1
     count : 1
     vpc_subnet_id : subnet-6561430d
     wait : yes
     assign_public_ip : yes